<a href="https://colab.research.google.com/github/FJR139/Digital-Skola-Learning/blob/main/Intro_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Declare array
a = np.array([1,2,3]) # vector
b = np.array([[1,2,3],[4,5,6]]) # matrix
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) # tensor
print(a)
print("\n")
print(b)
print("\n")
print(c)

[1 2 3]


[[1 2 3]
 [4 5 6]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# menentukan bentuk dari sebuah vector/matrix/tensor
vec_shape = np.shape(a)
mat_shape = np.shape(b)
tensor_shape = np.shape(c)
print(vec_shape)
print(mat_shape)
print(tensor_shape)

(3,)
(2, 3)
(3, 2, 2)


In [ ]:
# cara lain melihat shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 2, 2)


In [ ]:
# mengambil elemen yang spesifik (r,c)
print(b[1,1]) # mengambil elemen nomor 5 (1,1) indeksnya

5


In [ ]:
# mengambil kolom saja
print(b[:,1])

[2 5]


In [ ]:
# mengganti value dalam bentuk 2-D array / matrix
b[1,1] = 12
print(b)

[[ 1  2  3]
 [ 4 12  6]]


# Numpay Array types

## 1.Numpy array

In [ ]:
a_2 = np.array([4,5,6]) # vector
b_2 = np.array([[11,12,13],[14,15,16]]) # matrix

In [ ]:
print(a_2)
print(b_2)

[4 5 6]
[[11 12 13]
 [14 15 16]]


In [ ]:
b_2[1,1]

np.int64(15)

## 2.Numpy Arange

In [ ]:
# Function untuk mendefinisikan nilai2 yang berjarak sama dalam interval yang ditentukan dalam array tersebut
ar = np.arange(8) # start
print(ar)
ar2 = np.arange(1,8) # start stop
print(ar2)
ar3 = np.arange(1,12,3) # start stop step
print(ar3)

[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[ 1  4  7 10]


# Numpy Zeros

In [ ]:
#Function untuk menampilkan array baru dengan ukuran tertentu dan berisi 0
#defaultnya dtype adalah float
zeroes = np.zeros(5)
print(zeroes)
z2 = np.zeros((5,5), dtype=int)
print(z2)

[0. 0. 0. 0. 0.]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# Numpy Ones

In [ ]:
#Function untuk menampilkan array baru dengan ukuran tertentu dan berisi 1
#defaultnya dtype adalah float
ones = np.ones(5)
print(ones)
o2 = np.ones((3,4), dtype=int)
print(o2)

[1. 1. 1. 1. 1.]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Manipulasi Array

## 1.Reshape


In [ ]:
a = np.arange(1,13)
print(a)

# me re-shape Array menjadi matrix ordo 3x4
# cara cepat
b = a.reshape(3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2.Flatten

In [ ]:
# mengembalikan array menjadi bentuk 1-D array
# cara cepat
c = b.flatten()
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 3.Transpose

In [ ]:
#cara 1
# Transmat = np.array(b).transpose()
# print(Transmat)

#cara 2
Transmat = b.transpose()
print(Transmat)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**Axis/Axes** Digunakan untuk array yang lebih dari 1 dimensi


## 4.Concatenate

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[21,22,23],[24,25,26],[27,28,29]])

# concatenate dalam Axis 0
print("Concatenate 2 matrix dalam axis 0:") # default 0
print(np.concatenate((arr1,arr2),axis=0))

# concatenate dalam Axis 1
print("Concatenate 2 matrix dalam axis 1:") # Axis 1 itu menambah di kolom
print(np.concatenate((arr1,arr2),axis=1))

Concatenate 2 matrix dalam axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
Concatenate 2 matrix dalam axis 1:
[[ 1  2  3 21 22 23]
 [ 4  5  6 24 25 26]
 [ 7  8  9 27 28 29]]


## 5.Stack

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[21,22,23],[24,25,26],[27,28,29]])

#Stack dalam axis 0
print("Stack 2 array dalam axis 0:") # default 0
print(np.stack((arr1,arr2),axis=0))

#Stack dalam axis 1
print("\nStack 2 array dalam axis 1:")
print(np.stack((arr1,arr2),axis=1))

#Stack dalam axis -1
print("\nStack 2 array dalam axis -1:")
print(np.stack((arr1,arr2),axis=-1))

Stack 2 array dalam axis 0:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

Stack 2 array dalam axis 1:
[[[ 1  2  3]
  [21 22 23]]

 [[ 4  5  6]
  [24 25 26]]

 [[ 7  8  9]
  [27 28 29]]]

Stack 2 array dalam axis -1:
[[[ 1 21]
  [ 2 22]
  [ 3 23]]

 [[ 4 24]
  [ 5 25]
  [ 6 26]]

 [[ 7 27]
  [ 8 28]
  [ 9 29]]]


## 6.split

In [ ]:
SplitArr = np.array([5,2,3,4,8,7,6,2,3])
#Split array menjadi 3 bagian yang sama jumlahnya
SplitMat = np.split(SplitArr,3)
print(SplitMat)

#Split array di posisi index yang ditunjuk sesuai dengan 1-D array:
SplitMat2 = np.split(SplitArr,[1,3,5])
print(SplitMat2)

[array([5, 2, 3]), array([4, 8, 7]), array([6, 2, 3])]
[array([5]), array([2, 3]), array([4, 8]), array([7, 6, 2, 3])]


## 7.Resize

In [ ]:
#Mengubah size array, kalau size lebih besar maka terdapat salinan values
ResizeArr = np.array([[1,2,3],[4,5,6]])
ResizeMat = np.resize(ResizeArr,(3,5))
print(ResizeMat)

[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]]


## 8.Appeand

In [ ]:
InAppend = np.array([[1,2,3],[4,5,6]])

#Menggabungkan Array tanpa axis (1-D array)
Append1 = np.append(InAppend,[7,8,9])
print(Append1)

#Menggabungkan Array dengan axis 0
Append2 = np.append(InAppend,[[7,8,9]],axis=0)
print("\n", Append2)

#Menggabungkan Array dengan axis 1
Append3 = np.append(InAppend,[[7,8,9],[10,11,12]],axis=1)
print("\n", Append3)

[1 2 3 4 5 6 7 8 9]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## 9.Insert

In [ ]:
InArray = np.array([[1,2],[3,4],[5,6]])

#Insert tanpa axis, array akan di flatten (1-D Array)
Insert1 = np.insert(InArray, 2, [11,12])
print(Insert1)

#Insert axis 0
Insert2 = np.insert(InArray, 2, [11,12], axis=0)
print("\n", Insert2)

#Insert axis 1
Insert1 = np.insert(InArray, 2, [11,12,13], axis=1)
print("\n", Insert1)

[ 1  2 11 12  3  4  5  6]

 [[ 1  2]
 [ 3  4]
 [11 12]
 [ 5  6]]

 [[ 1  2 11]
 [ 3  4 12]
 [ 5  6 13]]


## 10.Delete

In [ ]:
from ast import Del
Indel = np.arange(1,9).reshape(2,4)
print(Indel)

#Delete tanpa axis, flatten ke 1-D Array
print("\n")
Delete = np.delete(Indel,2)
print(Delete)

#Delete axis 0 row ke-1 atau indeks 0 terhapus
Delete2 = np.delete(Indel,0,axis=0)
print("\n",Delete2)

#Delete axis 1, colmn terhapus
Delete3 = np.delete(Indel,1,axis=1)
print("\n",Delete3)

[[1 2 3 4]
 [5 6 7 8]]


[1 2 4 5 6 7 8]

 [[5 6 7 8]]

 [[1 3 4]
 [5 7 8]]


## 11.Unique

In [ ]:
InUnique = np.array([5,1,3,4,2,2,1,3,6,7,8,8,6])
print(InUnique)

#Value yang unik dari array
Unique1 = np.unique(InUnique)
print("\n",Unique1)

#Ada berapa value unik dari array
Unique2, indices = np.unique(InUnique, return_counts=True)
print("\nAda berapa value unik dalam array:")
print(Unique2)
print(indices)

[5 1 3 4 2 2 1 3 6 7 8 8 6]

 [1 2 3 4 5 6 7 8]

Ada berapa value unik dalam array:
[1 2 3 4 5 6 7 8]
[2 2 2 1 1 2 1 2]


## 12.Slice

In [ ]:
InSlice = np.arange(10)
print(InSlice)

#Slicing satu elemen
s2 = InSlice[2:]
print("\nSlicing dalam 1 elemen:")
print(s2)

#Slicing mulai dari indeks sekian...
s2 = InSlice[:2]
print("\nSlicing mulai dari indeks sekian:")
print(s2)

#Slicing stop pada indeks sekian...
s3 = InSlice[:5]
print("\nSlicing stop pada indeks sekian:")
print(s3)

#Slicing antara indeks-indeks sekian:
s4 = InSlice[2:5]
print("\nSlicing antara indeks-indeks sekian:")
print(s4)

#Slicing values dengan step/interval sekian...
print(InSlice)
s5 = InSlice[::2]
print("\nSlicing values dengan step/interval sekian:")
print(s5)

#Slicing dengan semua paramater...
s6 = InSlice[2:7:2]
print("\nSlicing dengan semua paramater:")
print(s6)

[0 1 2 3 4 5 6 7 8 9]

Slicing dalam 1 elemen:
[2 3 4 5 6 7 8 9]

Slicing mulai dari indeks sekian:
[0 1]

Slicing stop pada indeks sekian:
[0 1 2 3 4]

Slicing antara indeks-indeks sekian:
[2 3 4]
[0 1 2 3 4 5 6 7 8 9]

Slicing values dengan step/interval sekian:
[0 2 4 6 8]

Slicing dengan semua paramater:
[2 4 6]
